
name: Push

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: Build Project
        uses: hexagonkt/.github/.github/actions/gradle
